### ISSUE TITLE
Classes class doesn't exist, but is referenced in ClassGroup

### ISSUE THREAD

**Issue by ordago** [yungifez/schooldash#1]
https://github.com/yungifez/schooldash/blob/7acc5f25b13fb5b638685a2eb8597f664090f070/app/Models/ClassGroup.php#L23

Probably should be MyClass.

**Comment by yungifez** [comment]
Woahhh i didn't see that 🤣🤣🤣

**Comment by yungifez** [comment]
Fixed it

Thank you so much
