### ISSUE TITLE
Dynamic properties will be removed in php9, deprecated in php8.2

### ISSUE THREAD

**Issue by ordago** [yungifez/schooldash#20]
These properties are declared dynamically. Just a heads up in case you want to get ahead of this.

https://github.com/yungifez/schooldash/blob/147eb9fd644ccc1d8a52e6c88e67e596f7f1d4fa/app/Http/Livewire/ListTimetablesTable.php#L28-L30

Here is a link to the RFC:

https://wiki.php.net/rfc/deprecate_dynamic_properties

**Comment by yungifez** [comment]
Hey, what exact line 

Thanks for helping me

**Comment by ordago** [comment]
Both `classes` and `timetables` so that would be lines 28 and 30.
