### ISSUE TITLE
Question about docblocks

### ISSUE THREAD

**Issue by ordago** [yungifez/schooldash#51]
There are many instances where the type and name of the parameters don't coincide (`@param int $id` 31 times).

https://github.com/yungifez/schooldash/blob/ffa14abc2feaf51fd6fbc0dcbcb794846c2bc942/app/Http/Controllers/AcademicYearController.php#L58-L62

In this case the casing of the parameters in the docblocks and the parameters in the method is different:

https://github.com/yungifez/schooldash/blob/ffa14abc2feaf51fd6fbc0dcbcb794846c2bc942/app/Services/User/UserService.php#L100-L108

My question is, are you using the docblocks? or are they just automatically generated.

Would you accept a PR fixing or deleting them?

**Comment by yungifez** [comment]
Its auto generated with laravel resource controllers 

I never knew about the --model flag till recently when generating them 

A fix pr would be appreciated 

There's a lot on my plate with this project and things like that go un noticed

**Comment by yungifez** [comment]
Also would you like to be a moderator

**Comment by ordago** [comment]
If you don't use the docblocks you can publish the stubs of the controllers and remove them. That would be less visual noise.

No need to make a moderator. I can only participate from time to time.

Good luck!
