### ISSUE TITLE
Registration bug - cannot complete registration

### ISSUE THREAD

**Issue by OmegaMaxy** [yungifez/schooldash#9]
#### Description
When finishing the installation steps I tried to register a new account. And I received 8 validation messages/errors containing: "validation.required".

#### Screenshots
![image](https://user-images.githubusercontent.com/41763728/157093435-71261ead-79bb-41a4-84b1-dfb6d9ae8b2a.png)

#### Files
No relevant files.

#### To Reproduce
Enter homepage, change url to ``/register``.
Entered the following values for name, email and password respectively:
- root
- root@root.com
- root1234

**Comment by yungifez** [comment]
Imma probably delete that registration view

The app comes with default values

Students are to be added from the dashboard itself

**Comment by OmegaMaxy** [comment]
Oh alright, I get it now. This issue can be closed then.
